### PR TITLE
Add a more extensive readme.

### PR DESCRIPTION
**Pull request by bremoran**
cc @iriark01 @bogdanm

### CODE REVIEW

**Comment by iriark01** [comment]
Is this from the general mbed OS user guide?

**Comment by bremoran** [comment]
It's the text that I gave you for the user guide, yes.

**Comment by iriark01** [comment]
Awesome, then I shall ignore it.

**Comment by 0xc0170** [comment]
+1 for having this text in this readme

**Comment by bogdanm** [comment]
+1 from all my heart :)

**Comment by iriark01** [comment]
Please use this version:
https://github.com/ARMmbed/GettingStartedmbedOS/blob/master/Docs/Full_Guide/memory.md

It's post-editing.

**Comment by bremoran** [comment]
Updated with @iriark01's edited version

**Pull request merged**
