### PR TITLE
Fix deps

### PR DESCRIPTION
**Pull request by bogdanm**

### CODE REVIEW

**Comment by bogdanm** [comment]
*NOTE*: at this point, compilation will still fail because of all the dependencies between modules. I'm trying to resolve the dependencies bottom-up, which means code will likely not compile at all until I reach `mbed-drivers`.
Also I've included the commit created by `yotta version minor` to announce my intention of creating a new minor version as opposed to a patch. I find that to be the safest course of action.

@bremoran @0xc0170

**Comment by bremoran** [comment]
I'm not sure about the change to ```"core-util": ">=0.1.0"```.  Doesn't this reintroduce the need to propagate changes down the stack?

**Comment by bogdanm** [comment]
I don't think you can escape that. If you keep `"core-util": "*"` and your module has a `core-util` at version `0.0.x`, compilation will fail and you won't even get a "dependency not satisfied" error from yotta. At least this way the needed dependencies are fully encoded in this new `0.1.0` versoin of `ualloc`. I think it's OK to use '*' initially, but this needs to be updated when things change (like in this situation) to avoid compilation issues.

**Comment by bremoran** [comment]
Fair enough.

+1, then.

**Pull request merged**
